### PR TITLE
Extended functionality of entrypoint script

### PR DESCRIPTION
**Pull request by pr0ton11**
* Added functionality to add additional TS3Server arguments in the script
* Added functionality to statically set TS3 ServerAdmin password from environment

### CODE REVIEW

**Comment by mbentley** [comment]
I am trying to think if there is a cleaner way to do this.  Could you tell me specifically about the use case where passing the password as an environment variable is better than just passing it as an argument to the command line on your own?  My concern is that creating a one off environment variable for a configuration option that can either be set by passing the parameter or by creating an ini file, it means that there is now a 3rd pattern that only works for this one option.  Maybe if I understand how you'd like to use it, I can better think about it.

**Comment by pr0ton11** [comment]
I wanted to introduce the funcionality to easily define a server admin password without needing to read documentation of TS3 to find the corresponding parameters. This is used by my friends running some of their own TS3-Servers and they are not experts and neither is the target demographic that runs such a server, so they require an easy way (docker) to run it and set a serveradmin password (especially if they forget the former server admin password they can just look it up)

**Comment by exore13** [comment]
After formatting my computer I lost my superadmin group, next time I want to modify something on the server I will have to start from scratch, this is not the first time this happends...
It would have been pretty usefull to be able to change the superadmin password with this env variable.

**Comment by mbentley** [comment]
At the end of the day, I don't think supporting the environment variables like this makes sense unless all of them are supported.  The most logical way would be to do something like:
`TSPARAM-serveradmin_password` where there is an easily parseable prefix followed by the parameter name so that `TSPARAM-` could be stripped off and you're left with the actual parameter name.  I actually no longer personally use teamspeak and I wouldn't want to specifically maintain a whole list of variables to support every option so something that could simply do a loop through a list of variables would be the easiest.

**Review by WelcometoOz — APPROVED** [review]

**Pull request closed without merging**
